export {
  searchAppointmentsByAttribute,
  getAppointmentsForDate,
  getWaitlistedAppointments,
  getAppointmentSummary,
  getAppointmentBookingConflicts,
  bookAppointment,
  getLegacyAppointment,
  updateAppointment,
  updateAppointmentStatus,
  checkInAppointment,
  getAppointmentById,
  getUpcomingAppointments,
  getPastAppointments,
  getUpcomingAppointmentsPage,
  getPastAppointmentsPage,
  getAllAppointmentServices,
  getAppointmentService,
  saveAppointmentService,
  getFutureAppointmentsForServiceType,
  deleteAppointmentService,
  getAppointmentUnavailabilities,
  createAppointmentUnavailability,
} from './appointmentService';
export {
  type AppointmentPage,
  type AppointmentSummary,
  type AppointmentBookingConflicts,
  type AppointmentBookingRequest,
  type AppointmentUpdateRequest,
  type AppointmentService,
  type AppointmentAttribute,
  type AppointmentServiceAvailability,
  type AppointmentServiceType,
  type AppointmentServiceSaveRequest,
  type AppointmentUnavailability,
  type CheckInAppointmentResponse,
  type CreateUnavailabilityRequest,
} from './models';
export {
  APPOINTMENT_STATUSES,
  APPOINTMENT_IDENTIFIER_SYSTEM,
} from './constants';
