import {
  BankCandidates,
  BankCheckpoint,
  BankCheckpointDetail,
  BankDetail,
  BankEntry,
} from '../billingService';

export const bankCheckpoint = (): BankCheckpoint => ({
  id: 9,
  name: 'QorliaQA October checkpoint',
  reference: 'QorliaQA import reference',
  date: '2026-10-10',
  journal_id: [4, 'Bank INR'],
  company_id: [3, 'QorliaQA Isolated Billing'],
  currency_id: [1, 'INR'],
  balance_start: 50,
  balance_end: 150,
  balance_end_real: 150,
  is_complete: true,
  is_valid: false,
  problem_description: 'Previous ending balance does not match.',
});
export const checkpointDetail = (): BankCheckpointDetail => ({
  checkpoint_id: 9,
  checkpoint: bankCheckpoint(),
  version: 'a'.repeat(64),
  after: false,
  next_after: false,
  total_count: 1,
  rows: [{ ...bankEntry(), statement_id: [9, 'QorliaQA October checkpoint'] }],
});

export const bankEntry = (): BankEntry => ({
  id: 7,
  date: '2026-10-10',
  payment_ref: 'QorliaQA statement',
  partner_id: [8, 'QorliaQA Customer'],
  journal_id: [4, 'Bank INR'],
  statement_id: false,
  move_id: [17, 'BNK/2026/7'],
  state: 'posted',
  amount: 100,
  currency_id: [1, 'INR'],
  foreign_currency_id: false,
  amount_currency: 0,
  amount_residual: -100,
  is_reconciled: false,
});
export const bankDetail = (): BankDetail => ({
  statement_line_id: 7,
  version: 'a'.repeat(64),
  after: false,
  next_after: false,
  total_count: 2,
  entry: bankEntry(),
  company: 'QorliaQA Isolated Billing',
  company_currency: [1, 'INR'],
  debit: 100,
  credit: 100,
  balanced: true,
  rows: [
    {
      id: 71,
      name: 'Bank liquidity',
      account_id: [41, 'Bank account'],
      partner_id: [8, 'QorliaQA Customer'],
      date: '2026-10-10',
      debit: 100,
      credit: 0,
      balance: 100,
      currency_id: [1, 'INR'],
      amount_currency: 100,
      amount_residual: 0,
      amount_residual_currency: 0,
      reconciled: false,
      matching_number: false,
      kind: 'liquidity',
    },
    {
      id: 72,
      name: 'Statement suspense',
      account_id: [42, 'Suspense account'],
      partner_id: [8, 'QorliaQA Customer'],
      date: '2026-10-10',
      debit: 0,
      credit: 100,
      balance: -100,
      currency_id: [1, 'INR'],
      amount_currency: -100,
      amount_residual: -100,
      amount_residual_currency: -100,
      reconciled: false,
      matching_number: false,
      kind: 'suspense',
    },
  ],
});
export const bankCandidates = (): BankCandidates => ({
  statement_line_id: 7,
  version: 'a'.repeat(64),
  offset: 0,
  has_more: false,
  rows: [
    {
      id: 81,
      name: 'QorliaQA possible invoice',
      account_id: [43, 'Receivable'],
      partner_id: [8, 'QorliaQA Customer'],
      date: '2026-10-09',
      debit: 100,
      credit: 0,
      currency_id: [2, 'USD'],
      amount_currency: 2,
      amount_residual: 100,
      amount_residual_currency: 2,
      reconciled: false,
      move_id: [18, 'INV/2026/8'],
    },
  ],
});
