import { CustomerStatement } from '../billingService';

export const customerStatementFixture = (): CustomerStatement => ({
  invoice_id: 7,
  customer: 'QorliaQA Customer',
  company: 'QorliaQA Company',
  currency: [1, 'INR'],
  date_from: '2026-01-01',
  date_to: '2026-01-31',
  opening: 200,
  debit: 500,
  credit: 100,
  closing: 600,
  rows: [
    {
      id: 1,
      move_id: 7,
      date: '2026-01-02',
      document: 'INV/7',
      move_type: 'out_invoice',
      reference: false,
      label: 'Consultation',
      journal: 'Sales',
      account: 'Receivable',
      debit: 500,
      credit: 0,
      balance: 700,
      currency: [1, 'INR'],
      amount_currency: 500,
    },
    {
      id: 2,
      move_id: 9,
      date: '2026-01-03',
      document: 'PAY/9',
      move_type: 'entry',
      reference: 'Cash receipt',
      label: false,
      journal: 'Cash',
      account: 'Receivable',
      debit: 0,
      credit: 100,
      balance: 600,
      currency: [1, 'INR'],
      amount_currency: -100,
    },
  ],
});
