import { BillingDraft } from '../billingService';

export const draftFixture = (): BillingDraft => ({
  id: false,
  name: 'New charge order',
  version: false,
  values: {
    partner_id: 9,
    partner_invoice_id: 9,
    partner_shipping_id: 9,
    shop_id: 1,
    care_setting: 'opd',
    provider_name: false,
    client_order_ref: false,
    company_id: 1,
    pricelist_id: 1,
    warehouse_id: 1,
    location_id: 8,
    payment_term_id: 1,
    fiscal_position_id: false,
    date_order: '2026-10-09 10:00:00',
    discount_type: 'none',
    discount: 0,
    discount_percentage: 0,
    chargeable_amount: 0,
    disc_acc_id: false,
    note: false,
    partner_village: false,
    user_id: 3,
    team_id: false,
    validity_date: false,
  },
  lines: [
    {
      id: false,
      values: {
        product_id: 11,
        name: 'QorliaQA Consultation',
        display_type: false,
        sequence: 10,
        product_uom: 1,
        product_uom_qty: 1,
        price_unit: 500,
        discount: 0,
        tax_id: [],
        lot_id: false,
        expiry_date: false,
        analytic_distribution: false,
      },
      totals: { price_subtotal: 500, price_tax: 0, price_total: 500 },
    },
  ],
  totals: {
    amount_untaxed: 500,
    amount_tax: 0,
    amount_total: 500,
    round_off_amount: 0,
    currency_id: 21,
  },
  labels: {
    'res.currency:21': 'INR',
    'res.partner:9': 'QorliaQA Customer',
    'sale.shop:1': 'QorliaQA Shop',
    'product.product:11': 'QorliaQA Consultation',
    'uom.uom:1': 'Units',
  },
  warning: false,
});
