import { InvoiceDraft } from '../billingService';

export const invoiceDraftFixture = (): InvoiceDraft => ({
  id: 7,
  name: false,
  move_type: 'out_invoice',
  company: [1, 'QorliaQA Hospital'],
  version: 'a'.repeat(64),
  values: {
    partner_id: 9,
    partner_shipping_id: 9,
    ref: 'QorliaQA Draft',
    payment_reference: false,
    invoice_date: '2026-10-09',
    date: '2026-10-09',
    invoice_date_due: '2026-10-09',
    invoice_payment_term_id: false,
    journal_id: 1,
    currency_id: 21,
    fiscal_position_id: false,
    invoice_user_id: 3,
    partner_bank_id: false,
    invoice_incoterm_id: false,
    narration: false,
    discount_type: 'none',
    discount: 0,
    discount_percentage: 0,
    disc_acc_id: false,
    invoice_cash_rounding_id: false,
    auto_post: 'no',
    auto_post_until: false,
    to_check: false,
  },
  lines: [
    {
      id: 18,
      values: {
        product_id: 11,
        name: 'QorliaQA Consultation',
        display_type: 'product',
        sequence: 10,
        account_id: 13,
        product_uom_id: 1,
        quantity: 1,
        price_unit: 500,
        discount: 0,
        tax_ids: [],
        analytic_distribution: false,
      },
      totals: { price_subtotal: 500, price_total: 500 },
    },
  ],
  totals: {
    qorlia_item_subtotal: 500,
    amount_tax: 0,
    amount_total: 500,
    invoice_total: 500,
    round_off_amount: 0,
  },
  labels: {
    'res.currency:21': 'INR',
    'res.partner:9': 'QorliaQA Customer',
    'product.product:11': 'QorliaQA Consultation',
    'uom.uom:1': 'Units',
    'account.account:13': 'Service income',
  },
  warning: false,
  generated_adjustments: [],
  selections: {
    discount_type: [
      ['none', 'None'],
      ['fixed', 'Fixed'],
      ['percentage', 'Percentage'],
    ],
    auto_post: [
      ['no', 'No'],
      ['at_date', 'At date'],
      ['monthly', 'Monthly'],
      ['quarterly', 'Quarterly'],
      ['yearly', 'Yearly'],
    ],
  },
  journal_locked: false,
  can_edit: true,
});
