import { InvoiceJournal } from '../billingService';

export const invoiceJournalFixture = (): InvoiceJournal => ({
  invoice_id: 7,
  name: 'INV/QorliaQA/7',
  state: 'posted',
  journal: 'Customer invoices',
  company: 'QorliaQA Hospital',
  currency: [1, 'INR'],
  date: '2026-10-10',
  version: 'a'.repeat(64),
  after: false,
  next_after: false,
  total_count: 1,
  debit: 500,
  credit: 500,
  balanced: true,
  analytics_visible: false,
  rows: [
    {
      id: 17,
      name: 'QorliaQA Consultation',
      account_id: [5, '4000 Clinical income'],
      partner_id: [2, 'QorliaQA Patient'],
      date: '2026-10-10',
      date_maturity: false,
      debit: 0,
      credit: 500,
      balance: -500,
      currency_id: [1, 'INR'],
      amount_currency: -500,
      amount_residual: 0,
      amount_residual_currency: 0,
      reconciled: false,
      matching_number: false,
      tax_ids: [[3, 'QorliaQA Tax']],
      tax_tag_ids: [[4, 'QorliaQA Grid']],
      display_type: 'product',
      qorlia_adjustment_kind: false,
      analytic_distribution: false,
      can_cutoff: true,
    },
  ],
});
