import { JournalMoneyRequest, JournalMoneyView } from '../billingService';

export function moneyView(): JournalMoneyView {
  const values = {
    name: 'Consultation',
    account_id: 12,
    partner_id: 2,
    currency_id: 1,
    date_maturity: false as const,
    tax_tag_ids: [],
    analytic_distribution: false as const,
    discount_date: false as const,
    discount_amount_currency: 0,
    amount_currency: -500,
    debit: 0,
    credit: 500,
    balance: -500,
    tax_ids: [],
    product_id: 4,
    product_uom_id: 1,
    quantity: 1,
    price_unit: 500,
    price_subtotal: 500,
    price_total: 500,
    discount: 0,
    sequence: 10,
    display_type: 'product',
    qorlia_adjustment_kind: false as const,
    amount_residual: 0,
    amount_residual_currency: 0,
    reconciled: false,
    matched_debit_ids: [],
    matched_credit_ids: [],
    full_reconcile_id: false as const,
  };
  return {
    invoice_id: 7,
    name: 'INV/7',
    move_type: 'out_invoice',
    version: 'a'.repeat(64),
    company_currency: [1, 'INR'],
    transaction_currency: [1, 'INR'],
    can_edit: true,
    can_add: true,
    can_delete: false,
    editable_fields: [
      'name',
      'account_id',
      'partner_id',
      'currency_id',
      'amount_currency',
      'debit',
      'credit',
      'date_maturity',
      'discount_date',
      'discount_amount_currency',
      'tax_ids',
      'tax_tag_ids',
    ],
    labels: {
      'account.account:12': 'Consultation income',
      'account.account:13': 'Receivable',
      'res.partner:2': 'QorliaQA customer',
      'res.currency:1': 'INR',
      'product.product:4': 'Consultation',
      'uom.uom:1': 'Units',
    },
    totals: {
      state: 'posted',
      payment_state: 'not_paid',
      amount_untaxed: 500,
      amount_tax: 0,
      amount_total: 500,
      invoice_total: 500,
      amount_residual: 500,
    },
    rows: [
      { id: 14, values },
      {
        id: 15,
        values: {
          ...values,
          name: 'Payment term',
          account_id: 13,
          display_type: 'payment_term',
          amount_currency: 500,
          credit: 0,
          debit: 500,
          balance: 500,
        },
      },
    ],
  };
}
export function moneyRequest(): JournalMoneyRequest {
  return {
    payload: {
      invoice_id: 7,
      version: 'a'.repeat(64),
      changes: [{ id: 14, values: { credit: 600 } }],
    },
    review_version: 'b'.repeat(64),
    request_key: 'b99377b5-041a-41d7-89b7-596dfc58fb7c',
  };
}
